export const tagTypes = {
  USER: "User",
  ROLE: "Role",
  COMPANY: "Company",
  DEPARTMENT: "Department",
  RECRUITMENT: "Recruitment",
  SHIFT_SCHEDULE: "Shift_schedule",
  POLICY: "Policy",
  HOLIDAY: "Holiday",
  EMPLOYEE: "Employee",
  OVERTIME: "Overtime",
  LEAVE: "Leave",
  TICKET: "Ticket",
  ANNOUNCEMENT: "Announcement",
  CONSUMABLE: "Consumable",
  CERTIFICATION: "Certification",
};
