export const tagTypes = {
  USER: "User",
  ROLE: "Role",
  COMPANY: "Company",
  DEPARTMENT: "Department",
  RECRUITMENT: "Recruitment",
  SHIFT_SCHEDULE: "Shift_schedule",
  POLICY: "Policy",
  HOLIDAY: "Holiday",
  EMPLOYEE: "Employee",
  OVERTIME: "Overtime",
  OVERTIME_PAYMENT: 'OVERTIME_PAYMENT',
  LEAVE: "Leave",
  TICKET: "Ticket",
  ANNOUNCEMENT: "Announcement",
  CONSUMABLE: "Consumable",
  CERTIFICATION: "Certification",
  ATTENDANCE: "Attendance",
  HOME_OFFICE: "Home_office",
  PROFILE: "Profile",
  TANGIBLE: "Tangible",
  CATEGORY: "Category",
  LOAN: "Loan",
  CREDENTIALS: "Credentials",
  PAYROLL: "Payroll",
  TASK: "Task",
  MEETING: "Meeting",
};
